name: 'Grok artifacts'
description: 'Grok MINGW CI artifacts for removed DLLs or symbols required by reverse dependencies'
inputs:
  repo:
    description: 'sync database to search for reverse dependencies'
    required: false
    default: 'mingw64'
  path:
    description: 'Directory containing updated packages to grok'
    required: true
runs:
  using: 'composite'
  steps:

  - name: Install stuff
    shell: bash
    run: |
      echo "::group::Install stuff"
      python -m venv --system-site-packages grokker_venv
      . grokker_venv/bin/activate
      pip install -r '${{ github.action_path }}/../requirements.txt'
      deactivate
      echo "::endgroup::"
  - name: Grok packages
    shell: bash
    env:
      repo: ${{ inputs.repo }}
      packagepath: ${{ inputs.path }}
    run: |
      echo "::group::Grok packages"
      . grokker_venv/bin/activate
      python -u '${{ github.action_path }}/../package-update-check.py' -v -e "${repo,,}" artifact_dir "${packagepath}"
      echo "::endgroup::"
