name: Grok artifacts

on:
  workflow_call:
    inputs:
      msystem:
        description: 'Sync database to search for reverse dependencies'
        required: false
        default: 'MINGW64'
        type: string
      continue-on-artifact-error:
        description: 'Don''t fail job if download-artifact fails'
        required: false
        default: false
        type: boolean
      workflow-repository:
        description: 'Repository of the workflow you''re calling'
        required: false
        default: 'jeremyd2019/package-grokker'
        type: string
      workflow-ref:
        description: 'Ref of repository of the workflow you''re calling'
        required: false
        type: string

jobs:
  package-grokker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ inputs.workflow-repository }}
          ref: ${{ inputs.workflow-ref }}

      - id: workaround
        run: |
          echo 'continue-on-artifact-error=${{ inputs.continue-on-artifact-error }}' >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v4
        id: artifacts
        continue-on-error: ${{ steps.workaround.outputs.continue-on-artifact-error == 'true' }}
        with:
          name: ${{ inputs.msystem }}-packages
          path: artifacts

      - name: Grok packages
        uses: ./grok-artifacts
        if: steps.artifacts.outcome == 'success'
        with:
          repo: ${{ inputs.msystem }}
          path: artifacts
