# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repo:
        description: 'pacman repo name to search'
        required: true
        default: 'mingw64'
      package:
        description: 'package from which to find dependents'
        required: true
      dll:
        description: 'dll from which problematic symbols are imported'
        required: true
      symbols:
        description: 'problematic symbol(s)'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checker:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          release: true
          update: true
          msystem: MSYS
          install: python python-pyalpm
      - name: Grok packages
        shell: msys2 {0}
        run: |
          python -m venv --system-site-packages pefile
          . pefile/bin/activate
          pip install pefile
          mkdir /c/_
          python -u bla.py -t /c/_ -e '${{ github.event.inputs.repo }}' -p '${{ github.event.inputs.package }}' -d '${{ github.event.inputs.dll }}' ${{ github.event.inputs.symbols }}
