name: Manual search

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'pacman repo name to search'
        required: true
        default: 'mingw64'
      package:
        description: 'package from which to find dependents'
        required: true
      dll:
        description: 'dll(s) from which problematic symbols are imported'
        required: true
      symbols:
        description: 'problematic symbol(s)'
        required: false

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install stuff
        run: |
          python -m venv --system-site-packages venv
          . venv/bin/activate
          pip install -r requirements.txt
          deactivate
      - name: Grok packages
        run: |
          . venv/bin/activate
          dlls=""
          for d in ${{ github.event.inputs.dll }}; do
            dlls+=" -d $d"
          done
          python -u package-grokker.py -e '${{ github.event.inputs.repo }}' -p '${{ github.event.inputs.package }}' $dlls ${{ github.event.inputs.symbols }}
