name: Package update check

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'pacman repo name to search'
        required: true
        default: 'mingw64'
      package:
        description: 'package from which to find dependents'
        required: true
      old_url:
        description: 'url to old package version'
        required: true
      new_url:
        description: 'url to new package version'
        required: true

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Install stuff
        run: |
          python -m venv --system-site-packages venv
          . venv/bin/activate
          pip install -r requirements.txt
          deactivate
      - name: Grok packages
        run: |
          . venv/bin/activate
          python -u package-update-check.py -v -e '${{ github.event.inputs.repo }}' compare_urls -p '${{ github.event.inputs.package }}' '${{ github.event.inputs.old_url }}' '${{ github.event.inputs.new_url }}'
