name: PR update check

on:
  workflow_dispatch:
    inputs:
      msystem:
        description: 'MSYSTEM'
        required: true
        default: 'MINGW64'
        type: choice
        options:
        - MINGW64
        - MINGW32
        - UCRT64
        - CLANG64
        - CLANG32
        - CLANGARM64
      pr:
        description: 'PR number'
        required: true

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: msys2/MINGW-packages
          workflow: main.yml
          workflow_conclusion: ''
          pr: ${{ github.event.inputs.pr }}
          name: ${{ github.event.inputs.msystem }}-packages
          path: artifacts
          search_artifacts: true

      - name: Grok packages
        uses: ./grok-artifacts
        with:
          repo: ${{ github.event.inputs.msystem }}
          path: artifacts
